/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:18ca76d9-fcdf-4d5f-b173-24b1d2f19607",
    "aws_cognito_region": "ap-southeast-1",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [],
    "aws_mobile_analytics_app_id": "0b3a6e22b43d4fe5a2d03cff0712d726",
    "aws_mobile_analytics_app_region": "ap-southeast-1",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "0b3a6e22b43d4fe5a2d03cff0712d726",
            "region": "ap-southeast-1"
        }
    }
};


export default awsmobile
